[workspace]
resolver = "2"
members = [
  "journal_guest/guest",
  "deposit_guest/core",
  "deposit_guest/guest",
  "withdraw_guest/core",
  "withdraw_guest/guest",
  "witness_fixture/cli",
]

default-members = [
  "deposit_guest/core",
  "withdraw_guest/core",
]
