[workspace]
resolver = "2"
members = [
  "deposit_guest/core",
  "deposit_guest/guest",
  "withdraw_guest/core",
  "withdraw_guest/guest",
]

default-members = [
  "deposit_guest/core",
  "withdraw_guest/core",
]
