[package]
name = "deposit-guest"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = { version = "1.5.0", default-features = false }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
