[package]
name = "withdraw-guest"
version = "0.1.0"
edition = "2024"

[dependencies]
withdraw-guest-core = { path = "../core" }
orchard = { version = "0.12.0", default-features = false }
sp1-zkvm = { version = "6.0.1" }
